### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by AdrianKriger** [rsbivand/spgwr#3]
Can you open a Discussion please?

The challenge might not be an issue. i.e.: can be resolved through dialogue or simple Q and A.

**Comment by rsbivand** [comment]
Please motivate. This package will not be maintained by me, and I will not answer questions on GWR, as the package was largely written to point out serious challenges in the inferential use of a strictly exploratory approach (IMO).

**Comment by AdrianKriger** [comment]
Your level of service is excellent. Thank you for the extremely prompt response. 

Forgive my tardiness.
I can only communicate effectively in the new week [7 Aug. onward].

**Comment by AdrianKriger** [comment]
I want the Columbus data via the `spgwr` package but I can't `conda` install `r-spgwr`.
Is this package not available via `conda`? I mean in a duel python / R environment.

**Comment by rsbivand** [comment]
Why? The Columbus data set is not included in this package at all. Canonically, it is at https://geodacenter.github.io/data-and-lab/columbus/. In R, it is included in `spData`, and in another version in `spdep`, and possibly elsewhere.

**Comment by AdrianKriger** [comment]
I am mistaken. Is `spgwr` available via conda? As an `r-spgwr` package?

**Comment by rsbivand** [comment]
No idea. Why should it be? It is available through all standard distribution mechanisms for R packages (CRAN is the standard mechanism). Beyond CRAN, it is completely the problem of the user if they choose a non-standard mechanism.

**Comment by AdrianKriger** [comment]
You have been extremely patient and considerate. Thank you.
