### ISSUE TITLE
Add AICc as a method for bandwidth optimization

### ISSUE THREAD

**Issue by Aariq** [rsbivand/spgwr#4]
In Comber et al. (2023), they suggest using AICc over AIC or CV methods for choosing bandwidth:

>Bandwidths found by AICc are preferred to those found by CV and uncorrected AIC because it reflects model parsimony adjusted for small degrees of freedom and its use tends to avoid overfitting GWR models (AICc bandwidths tend to be larger than bandwidths found using CV and AIC)

Would it make sense to add this as an option?  An `AICc()` function is available in `bbmle` and several other R packages.

Comber, A., Brunsdon, C., Charlton, M., Dong, G., Harris, R., Lu, B., Lü, Y., Murakami, D., Nakaya, T., Wang, Y., Harris, P., 2023. A Route Map for Successful Applications of Geographically Weighted Regression. Geographical Analysis 55, 155–178. https://doi.org/10.1111/gean.12316

**Comment by rsbivand** [comment]
This package is close to end of life, ans any fixes will only be to fix avoidable breakages. As soon as the remaining packages importing `spgwr` cease to do so, it will be archived. Pleas use `GWmodel` instead if you want to use AICc - it is used in that package.
